# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/andrew/ece527/mp2/mp2a.cache/wt [current_project]
set_property parent.project_path /home/andrew/ece527/mp2/mp2a.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/andrew/ece527/mp2/mp2a.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/andrew/ece527/mp2/charLib.coe
read_verilog -library xil_defaultlib /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/hdl/mp1a_hardware_wrapper.v
add_files /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/mp1a_hardware.bd
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_processing_system7_0_0/mp1a_hardware_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_axi_gpio_0_0/mp1a_hardware_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_axi_gpio_0_0/mp1a_hardware_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_axi_gpio_0_0/mp1a_hardware_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_rst_ps7_0_100M_0/mp1a_hardware_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_rst_ps7_0_100M_0/mp1a_hardware_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_rst_ps7_0_100M_0/mp1a_hardware_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_axi_gpio_1_0/mp1a_hardware_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_axi_gpio_1_0/mp1a_hardware_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_axi_gpio_1_0/mp1a_hardware_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_xbar_0/mp1a_hardware_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_blk_mem_gen_0_0/mp1a_hardware_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_auto_pc_0/mp1a_hardware_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/mp1a_hardware_ooc.xdc]
set_property is_locked true [get_files /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/mp1a_hardware.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/andrew/ece527/mp2/mp2a.srcs/constrs_1/new/pinout.xdc
set_property used_in_implementation false [get_files /home/andrew/ece527/mp2/mp2a.srcs/constrs_1/new/pinout.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mp1a_hardware_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef mp1a_hardware_wrapper.dcp

catch { report_utilization -file mp1a_hardware_wrapper_utilization_synth.rpt -pb mp1a_hardware_wrapper_utilization_synth.pb }
