// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCONVOLUTION5_H
#define XCONVOLUTION5_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xconvolution5_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XConvolution5_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XConvolution5;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XConvolution5_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XConvolution5_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XConvolution5_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XConvolution5_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XConvolution5_Initialize(XConvolution5 *InstancePtr, u16 DeviceId);
XConvolution5_Config* XConvolution5_LookupConfig(u16 DeviceId);
int XConvolution5_CfgInitialize(XConvolution5 *InstancePtr, XConvolution5_Config *ConfigPtr);
#else
int XConvolution5_Initialize(XConvolution5 *InstancePtr, const char* InstanceName);
int XConvolution5_Release(XConvolution5 *InstancePtr);
#endif

void XConvolution5_Start(XConvolution5 *InstancePtr);
u32 XConvolution5_IsDone(XConvolution5 *InstancePtr);
u32 XConvolution5_IsIdle(XConvolution5 *InstancePtr);
u32 XConvolution5_IsReady(XConvolution5 *InstancePtr);
void XConvolution5_EnableAutoRestart(XConvolution5 *InstancePtr);
void XConvolution5_DisableAutoRestart(XConvolution5 *InstancePtr);
u32 XConvolution5_Get_return(XConvolution5 *InstancePtr);

void XConvolution5_Set_input_r(XConvolution5 *InstancePtr, u32 Data);
u32 XConvolution5_Get_input_r(XConvolution5 *InstancePtr);
void XConvolution5_Set_weights(XConvolution5 *InstancePtr, u32 Data);
u32 XConvolution5_Get_weights(XConvolution5 *InstancePtr);
void XConvolution5_Set_bias(XConvolution5 *InstancePtr, u32 Data);
u32 XConvolution5_Get_bias(XConvolution5 *InstancePtr);
void XConvolution5_Set_output_r(XConvolution5 *InstancePtr, u32 Data);
u32 XConvolution5_Get_output_r(XConvolution5 *InstancePtr);

void XConvolution5_InterruptGlobalEnable(XConvolution5 *InstancePtr);
void XConvolution5_InterruptGlobalDisable(XConvolution5 *InstancePtr);
void XConvolution5_InterruptEnable(XConvolution5 *InstancePtr, u32 Mask);
void XConvolution5_InterruptDisable(XConvolution5 *InstancePtr, u32 Mask);
void XConvolution5_InterruptClear(XConvolution5 *InstancePtr, u32 Mask);
u32 XConvolution5_InterruptGetEnabled(XConvolution5 *InstancePtr);
u32 XConvolution5_InterruptGetStatus(XConvolution5 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
