// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xconvolution5.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XConvolution5_CfgInitialize(XConvolution5 *InstancePtr, XConvolution5_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XConvolution5_Start(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_AP_CTRL) & 0x80;
    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XConvolution5_IsDone(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XConvolution5_IsIdle(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XConvolution5_IsReady(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XConvolution5_EnableAutoRestart(XConvolution5 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XConvolution5_DisableAutoRestart(XConvolution5 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XConvolution5_Get_return(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XConvolution5_Set_input_r(XConvolution5 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_INPUT_R_DATA, Data);
}

u32 XConvolution5_Get_input_r(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_INPUT_R_DATA);
    return Data;
}

void XConvolution5_Set_weights(XConvolution5 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_WEIGHTS_DATA, Data);
}

u32 XConvolution5_Get_weights(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_WEIGHTS_DATA);
    return Data;
}

void XConvolution5_Set_bias(XConvolution5 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_BIAS_DATA, Data);
}

u32 XConvolution5_Get_bias(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_BIAS_DATA);
    return Data;
}

void XConvolution5_Set_output_r(XConvolution5 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_OUTPUT_R_DATA, Data);
}

u32 XConvolution5_Get_output_r(XConvolution5 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_OUTPUT_R_DATA);
    return Data;
}

void XConvolution5_InterruptGlobalEnable(XConvolution5 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_GIE, 1);
}

void XConvolution5_InterruptGlobalDisable(XConvolution5 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_GIE, 0);
}

void XConvolution5_InterruptEnable(XConvolution5 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_IER);
    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_IER, Register | Mask);
}

void XConvolution5_InterruptDisable(XConvolution5 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_IER);
    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_IER, Register & (~Mask));
}

void XConvolution5_InterruptClear(XConvolution5 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolution5_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_ISR, Mask);
}

u32 XConvolution5_InterruptGetEnabled(XConvolution5 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_IER);
}

u32 XConvolution5_InterruptGetStatus(XConvolution5 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConvolution5_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVOLUTION5_AXILITES_ADDR_ISR);
}

