// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCONVOLUTION1_H
#define XCONVOLUTION1_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xconvolution1_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XConvolution1_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XConvolution1;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XConvolution1_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XConvolution1_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XConvolution1_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XConvolution1_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XConvolution1_Initialize(XConvolution1 *InstancePtr, u16 DeviceId);
XConvolution1_Config* XConvolution1_LookupConfig(u16 DeviceId);
int XConvolution1_CfgInitialize(XConvolution1 *InstancePtr, XConvolution1_Config *ConfigPtr);
#else
int XConvolution1_Initialize(XConvolution1 *InstancePtr, const char* InstanceName);
int XConvolution1_Release(XConvolution1 *InstancePtr);
#endif

void XConvolution1_Start(XConvolution1 *InstancePtr);
u32 XConvolution1_IsDone(XConvolution1 *InstancePtr);
u32 XConvolution1_IsIdle(XConvolution1 *InstancePtr);
u32 XConvolution1_IsReady(XConvolution1 *InstancePtr);
void XConvolution1_EnableAutoRestart(XConvolution1 *InstancePtr);
void XConvolution1_DisableAutoRestart(XConvolution1 *InstancePtr);
u32 XConvolution1_Get_return(XConvolution1 *InstancePtr);

void XConvolution1_Set_input_r(XConvolution1 *InstancePtr, u32 Data);
u32 XConvolution1_Get_input_r(XConvolution1 *InstancePtr);
void XConvolution1_Set_weights(XConvolution1 *InstancePtr, u32 Data);
u32 XConvolution1_Get_weights(XConvolution1 *InstancePtr);
void XConvolution1_Set_bias(XConvolution1 *InstancePtr, u32 Data);
u32 XConvolution1_Get_bias(XConvolution1 *InstancePtr);
void XConvolution1_Set_output_r(XConvolution1 *InstancePtr, u32 Data);
u32 XConvolution1_Get_output_r(XConvolution1 *InstancePtr);

void XConvolution1_InterruptGlobalEnable(XConvolution1 *InstancePtr);
void XConvolution1_InterruptGlobalDisable(XConvolution1 *InstancePtr);
void XConvolution1_InterruptEnable(XConvolution1 *InstancePtr, u32 Mask);
void XConvolution1_InterruptDisable(XConvolution1 *InstancePtr, u32 Mask);
void XConvolution1_InterruptClear(XConvolution1 *InstancePtr, u32 Mask);
u32 XConvolution1_InterruptGetEnabled(XConvolution1 *InstancePtr);
u32 XConvolution1_InterruptGetStatus(XConvolution1 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
