// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "convolution3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic convolution3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic convolution3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<25> convolution3::ap_ST_fsm_state1 = "1";
const sc_lv<25> convolution3::ap_ST_fsm_state2 = "10";
const sc_lv<25> convolution3::ap_ST_fsm_state3 = "100";
const sc_lv<25> convolution3::ap_ST_fsm_state4 = "1000";
const sc_lv<25> convolution3::ap_ST_fsm_state5 = "10000";
const sc_lv<25> convolution3::ap_ST_fsm_state6 = "100000";
const sc_lv<25> convolution3::ap_ST_fsm_state7 = "1000000";
const sc_lv<25> convolution3::ap_ST_fsm_state8 = "10000000";
const sc_lv<25> convolution3::ap_ST_fsm_state9 = "100000000";
const sc_lv<25> convolution3::ap_ST_fsm_state10 = "1000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state11 = "10000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state12 = "100000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<25> convolution3::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<32> convolution3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> convolution3::ap_const_lv32_1 = "1";
const sc_lv<1> convolution3::ap_const_lv1_0 = "0";
const sc_lv<32> convolution3::ap_const_lv32_2 = "10";
const sc_lv<32> convolution3::ap_const_lv32_3 = "11";
const sc_lv<32> convolution3::ap_const_lv32_4 = "100";
const sc_lv<32> convolution3::ap_const_lv32_5 = "101";
const sc_lv<32> convolution3::ap_const_lv32_6 = "110";
const sc_lv<32> convolution3::ap_const_lv32_7 = "111";
const sc_lv<1> convolution3::ap_const_lv1_1 = "1";
const sc_lv<32> convolution3::ap_const_lv32_8 = "1000";
const sc_lv<32> convolution3::ap_const_lv32_C = "1100";
const sc_lv<32> convolution3::ap_const_lv32_11 = "10001";
const sc_lv<32> convolution3::ap_const_lv32_12 = "10010";
const sc_lv<32> convolution3::ap_const_lv32_17 = "10111";
const sc_lv<5> convolution3::ap_const_lv5_0 = "00000";
const sc_lv<4> convolution3::ap_const_lv4_0 = "0000";
const sc_lv<32> convolution3::ap_const_lv32_18 = "11000";
const sc_lv<3> convolution3::ap_const_lv3_0 = "000";
const sc_lv<32> convolution3::ap_const_lv32_D = "1101";
const sc_lv<32> convolution3::ap_const_lv32_13 = "10011";
const sc_lv<32> convolution3::ap_const_lv32_9 = "1001";
const sc_lv<5> convolution3::ap_const_lv5_10 = "10000";
const sc_lv<5> convolution3::ap_const_lv5_1 = "1";
const sc_lv<4> convolution3::ap_const_lv4_A = "1010";
const sc_lv<4> convolution3::ap_const_lv4_1 = "1";
const sc_lv<4> convolution3::ap_const_lv4_5 = "101";
const sc_lv<2> convolution3::ap_const_lv2_0 = "00";
const sc_lv<3> convolution3::ap_const_lv3_6 = "110";
const sc_lv<3> convolution3::ap_const_lv3_1 = "1";
const bool convolution3::ap_const_boolean_1 = true;

convolution3::convolution3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lenet_wrapper_fadbkb_x_U30 = new lenet_wrapper_fadbkb<1,5,32,32,32>("lenet_wrapper_fadbkb_x_U30");
    lenet_wrapper_fadbkb_x_U30->clk(ap_clk);
    lenet_wrapper_fadbkb_x_U30->reset(ap_rst);
    lenet_wrapper_fadbkb_x_U30->din0(grp_fu_235_p0);
    lenet_wrapper_fadbkb_x_U30->din1(grp_fu_235_p1);
    lenet_wrapper_fadbkb_x_U30->ce(ap_var_for_const0);
    lenet_wrapper_fadbkb_x_U30->dout(grp_fu_235_p2);
    lenet_wrapper_fmucud_x_U31 = new lenet_wrapper_fmucud<1,4,32,32,32>("lenet_wrapper_fmucud_x_U31");
    lenet_wrapper_fmucud_x_U31->clk(ap_clk);
    lenet_wrapper_fmucud_x_U31->reset(ap_rst);
    lenet_wrapper_fmucud_x_U31->din0(conv3_w_load_reg_746);
    lenet_wrapper_fmucud_x_U31->din1(p2_o_2_load_reg_751);
    lenet_wrapper_fmucud_x_U31->ce(ap_var_for_const0);
    lenet_wrapper_fmucud_x_U31->dout(grp_fu_241_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_290_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_290_p2 );

    SC_METHOD(thread_ci_2_fu_538_p2);
    sensitive << ( ci_reg_212 );

    SC_METHOD(thread_ci_cast1_cast_fu_439_p1);
    sensitive << ( ci_reg_212 );

    SC_METHOD(thread_co_2_fu_296_p2);
    sensitive << ( co_reg_112 );

    SC_METHOD(thread_co_cast4_fu_245_p1);
    sensitive << ( co_reg_112 );

    SC_METHOD(thread_conv3_b_address0);
    sensitive << ( conv3_b_addr_reg_620 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_conv3_b_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_conv3_w_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_181_cast_fu_561_p1 );

    SC_METHOD(thread_conv3_w_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_exitcond1_fu_381_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j_reg_134 );

    SC_METHOD(thread_exitcond2_fu_341_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_reg_123 );

    SC_METHOD(thread_exitcond3_fu_290_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( co_reg_112 );

    SC_METHOD(thread_exitcond_fu_532_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ci_reg_212 );

    SC_METHOD(thread_grp_fu_235_p0);
    sensitive << ( sum_reg_167 );
    sensitive << ( sum_2_reg_223 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_grp_fu_235_p1);
    sensitive << ( tmp_22_reg_756 );
    sensitive << ( conv3_b_load_reg_766 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_h_fu_347_p2);
    sensitive << ( i_reg_123 );

    SC_METHOD(thread_i_18_fu_433_p2);
    sensitive << ( i17_reg_145 );

    SC_METHOD(thread_i_cast3_cast_fu_306_p1);
    sensitive << ( i_reg_123 );

    SC_METHOD(thread_i_cast3_fu_302_p1);
    sensitive << ( i_reg_123 );

    SC_METHOD(thread_j_13_fu_596_p2);
    sensitive << ( j12_reg_179 );

    SC_METHOD(thread_j_cast2_cast_fu_367_p1);
    sensitive << ( j_reg_134 );

    SC_METHOD(thread_j_cast2_fu_363_p1);
    sensitive << ( j_reg_134 );

    SC_METHOD(thread_m_1_fu_408_p2);
    sensitive << ( m_reg_155 );

    SC_METHOD(thread_n_1_fu_427_p2);
    sensitive << ( n_reg_189 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( output_addr_reg_653 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( tmp_20_reg_771 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_p2_o_2_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_189_cast_fu_591_p1 );

    SC_METHOD(thread_p2_o_2_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_p_shl10_cast_fu_544_p3);
    sensitive << ( tmp_153_reg_707 );

    SC_METHOD(thread_p_shl2_cast_fu_258_p1);
    sensitive << ( tmp_155_fu_250_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_270_p1);
    sensitive << ( tmp_156_fu_262_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_315_p3);
    sensitive << ( tmp_159_fu_310_p2 );

    SC_METHOD(thread_p_shl5_cast_fu_331_p1);
    sensitive << ( tmp_148_fu_323_p3 );

    SC_METHOD(thread_p_shl6_cast_fu_566_p3);
    sensitive << ( tmp_154_reg_712 );

    SC_METHOD(thread_p_shl7_cast_fu_573_p3);
    sensitive << ( tmp_171_reg_717 );

    SC_METHOD(thread_p_shl8_cast_fu_492_p1);
    sensitive << ( tmp_167_fu_484_p3 );

    SC_METHOD(thread_p_shl9_cast_fu_504_p1);
    sensitive << ( tmp_168_fu_496_p3 );

    SC_METHOD(thread_p_shl_fu_460_p1);
    sensitive << ( tmp_151_fu_452_p3 );

    SC_METHOD(thread_tmp_148_fu_323_p3);
    sensitive << ( tmp_159_fu_310_p2 );

    SC_METHOD(thread_tmp_149_fu_414_p1);
    sensitive << ( j12_reg_179 );

    SC_METHOD(thread_tmp_150_fu_418_p1);
    sensitive << ( n_reg_189 );

    SC_METHOD(thread_tmp_151_fu_452_p3);
    sensitive << ( tmp_162_fu_443_p2 );

    SC_METHOD(thread_tmp_152_fu_476_p1);
    sensitive << ( tmp_164_fu_470_p2 );

    SC_METHOD(thread_tmp_153_fu_480_p1);
    sensitive << ( tmp_164_fu_470_p2 );

    SC_METHOD(thread_tmp_154_fu_524_p1);
    sensitive << ( tmp_170_fu_518_p2 );

    SC_METHOD(thread_tmp_155_fu_250_p3);
    sensitive << ( co_reg_112 );

    SC_METHOD(thread_tmp_156_fu_262_p3);
    sensitive << ( co_reg_112 );

    SC_METHOD(thread_tmp_157_fu_274_p2);
    sensitive << ( p_shl2_cast_fu_258_p1 );
    sensitive << ( p_shl3_cast_fu_270_p1 );

    SC_METHOD(thread_tmp_158_fu_284_p2);
    sensitive << ( p_shl2_cast_fu_258_p1 );
    sensitive << ( p_shl3_cast_fu_270_p1 );

    SC_METHOD(thread_tmp_159_fu_310_p2);
    sensitive << ( tmp_158_reg_607 );
    sensitive << ( i_cast3_cast_fu_306_p1 );

    SC_METHOD(thread_tmp_160_fu_335_p2);
    sensitive << ( p_shl4_cast_fu_315_p3 );
    sensitive << ( p_shl5_cast_fu_331_p1 );

    SC_METHOD(thread_tmp_161_fu_371_p2);
    sensitive << ( tmp_160_reg_630 );
    sensitive << ( j_cast2_cast_fu_367_p1 );

    SC_METHOD(thread_tmp_162_fu_443_p2);
    sensitive << ( tmp_166_cast_reg_602 );
    sensitive << ( ci_cast1_cast_fu_439_p1 );

    SC_METHOD(thread_tmp_163_fu_464_p2);
    sensitive << ( p_shl_fu_460_p1 );
    sensitive << ( tmp_175_cast_fu_448_p1 );

    SC_METHOD(thread_tmp_164_fu_470_p2);
    sensitive << ( m_reg_155 );
    sensitive << ( tmp_163_fu_464_p2 );

    SC_METHOD(thread_tmp_165_fu_551_p2);
    sensitive << ( tmp_152_reg_702 );
    sensitive << ( p_shl10_cast_fu_544_p3 );

    SC_METHOD(thread_tmp_166_cast_fu_280_p1);
    sensitive << ( tmp_157_fu_274_p2 );

    SC_METHOD(thread_tmp_166_fu_556_p2);
    sensitive << ( tmp_150_reg_684 );
    sensitive << ( tmp_165_fu_551_p2 );

    SC_METHOD(thread_tmp_167_fu_484_p3);
    sensitive << ( ci_reg_212 );

    SC_METHOD(thread_tmp_168_fu_496_p3);
    sensitive << ( ci_reg_212 );

    SC_METHOD(thread_tmp_169_fu_508_p2);
    sensitive << ( p_shl8_cast_fu_492_p1 );
    sensitive << ( p_shl9_cast_fu_504_p1 );

    SC_METHOD(thread_tmp_170_fu_518_p2);
    sensitive << ( i17_reg_145 );
    sensitive << ( tmp_184_cast_fu_514_p1 );

    SC_METHOD(thread_tmp_171_fu_528_p1);
    sensitive << ( tmp_170_fu_518_p2 );

    SC_METHOD(thread_tmp_172_fu_580_p2);
    sensitive << ( p_shl6_cast_fu_566_p3 );
    sensitive << ( p_shl7_cast_fu_573_p3 );

    SC_METHOD(thread_tmp_173_fu_586_p2);
    sensitive << ( tmp_149_reg_679 );
    sensitive << ( tmp_172_fu_580_p2 );

    SC_METHOD(thread_tmp_174_cast_fu_376_p1);
    sensitive << ( tmp_161_fu_371_p2 );

    SC_METHOD(thread_tmp_175_cast_fu_448_p1);
    sensitive << ( tmp_162_fu_443_p2 );

    SC_METHOD(thread_tmp_181_cast_fu_561_p1);
    sensitive << ( tmp_166_fu_556_p2 );

    SC_METHOD(thread_tmp_184_cast_fu_514_p1);
    sensitive << ( tmp_169_fu_508_p2 );

    SC_METHOD(thread_tmp_189_cast_fu_591_p1);
    sensitive << ( tmp_173_fu_586_p2 );

    SC_METHOD(thread_tmp_19_fu_403_p2);
    sensitive << ( tmp_cast_reg_643 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i17_reg_145 );

    SC_METHOD(thread_tmp_21_fu_422_p2);
    sensitive << ( tmp_cast_81_reg_666 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j12_reg_179 );

    SC_METHOD(thread_tmp_cast_81_fu_399_p1);
    sensitive << ( tmp_s_fu_393_p2 );

    SC_METHOD(thread_tmp_cast_fu_359_p1);
    sensitive << ( tmp_fu_353_p2 );

    SC_METHOD(thread_tmp_fu_353_p2);
    sensitive << ( i_reg_123 );

    SC_METHOD(thread_tmp_s_fu_393_p2);
    sensitive << ( j_reg_134 );

    SC_METHOD(thread_w_fu_387_p2);
    sensitive << ( j_reg_134 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_290_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_341_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond1_fu_381_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_21_fu_422_p2 );
    sensitive << ( exitcond_reg_722 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_19_fu_403_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "convolution3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, conv3_w_address0, "(port)conv3_w_address0");
    sc_trace(mVcdFile, conv3_w_ce0, "(port)conv3_w_ce0");
    sc_trace(mVcdFile, conv3_w_q0, "(port)conv3_w_q0");
    sc_trace(mVcdFile, conv3_b_address0, "(port)conv3_b_address0");
    sc_trace(mVcdFile, conv3_b_ce0, "(port)conv3_b_ce0");
    sc_trace(mVcdFile, conv3_b_q0, "(port)conv3_b_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, p2_o_2_address0, "(port)p2_o_2_address0");
    sc_trace(mVcdFile, p2_o_2_ce0, "(port)p2_o_2_ce0");
    sc_trace(mVcdFile, p2_o_2_q0, "(port)p2_o_2_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_166_cast_fu_280_p1, "tmp_166_cast_fu_280_p1");
    sc_trace(mVcdFile, tmp_166_cast_reg_602, "tmp_166_cast_reg_602");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_158_fu_284_p2, "tmp_158_fu_284_p2");
    sc_trace(mVcdFile, tmp_158_reg_607, "tmp_158_reg_607");
    sc_trace(mVcdFile, co_2_fu_296_p2, "co_2_fu_296_p2");
    sc_trace(mVcdFile, co_2_reg_615, "co_2_reg_615");
    sc_trace(mVcdFile, conv3_b_addr_reg_620, "conv3_b_addr_reg_620");
    sc_trace(mVcdFile, exitcond3_fu_290_p2, "exitcond3_fu_290_p2");
    sc_trace(mVcdFile, i_cast3_fu_302_p1, "i_cast3_fu_302_p1");
    sc_trace(mVcdFile, i_cast3_reg_625, "i_cast3_reg_625");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_160_fu_335_p2, "tmp_160_fu_335_p2");
    sc_trace(mVcdFile, tmp_160_reg_630, "tmp_160_reg_630");
    sc_trace(mVcdFile, h_fu_347_p2, "h_fu_347_p2");
    sc_trace(mVcdFile, h_reg_638, "h_reg_638");
    sc_trace(mVcdFile, tmp_cast_fu_359_p1, "tmp_cast_fu_359_p1");
    sc_trace(mVcdFile, tmp_cast_reg_643, "tmp_cast_reg_643");
    sc_trace(mVcdFile, exitcond2_fu_341_p2, "exitcond2_fu_341_p2");
    sc_trace(mVcdFile, j_cast2_fu_363_p1, "j_cast2_fu_363_p1");
    sc_trace(mVcdFile, j_cast2_reg_648, "j_cast2_reg_648");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, output_addr_reg_653, "output_addr_reg_653");
    sc_trace(mVcdFile, w_fu_387_p2, "w_fu_387_p2");
    sc_trace(mVcdFile, w_reg_661, "w_reg_661");
    sc_trace(mVcdFile, tmp_cast_81_fu_399_p1, "tmp_cast_81_fu_399_p1");
    sc_trace(mVcdFile, tmp_cast_81_reg_666, "tmp_cast_81_reg_666");
    sc_trace(mVcdFile, exitcond1_fu_381_p2, "exitcond1_fu_381_p2");
    sc_trace(mVcdFile, m_1_fu_408_p2, "m_1_fu_408_p2");
    sc_trace(mVcdFile, m_1_reg_674, "m_1_reg_674");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_149_fu_414_p1, "tmp_149_fu_414_p1");
    sc_trace(mVcdFile, tmp_149_reg_679, "tmp_149_reg_679");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_150_fu_418_p1, "tmp_150_fu_418_p1");
    sc_trace(mVcdFile, tmp_150_reg_684, "tmp_150_reg_684");
    sc_trace(mVcdFile, n_1_fu_427_p2, "n_1_fu_427_p2");
    sc_trace(mVcdFile, n_1_reg_692, "n_1_reg_692");
    sc_trace(mVcdFile, i_18_fu_433_p2, "i_18_fu_433_p2");
    sc_trace(mVcdFile, tmp_21_fu_422_p2, "tmp_21_fu_422_p2");
    sc_trace(mVcdFile, tmp_152_fu_476_p1, "tmp_152_fu_476_p1");
    sc_trace(mVcdFile, tmp_152_reg_702, "tmp_152_reg_702");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_153_fu_480_p1, "tmp_153_fu_480_p1");
    sc_trace(mVcdFile, tmp_153_reg_707, "tmp_153_reg_707");
    sc_trace(mVcdFile, tmp_154_fu_524_p1, "tmp_154_fu_524_p1");
    sc_trace(mVcdFile, tmp_154_reg_712, "tmp_154_reg_712");
    sc_trace(mVcdFile, tmp_171_fu_528_p1, "tmp_171_fu_528_p1");
    sc_trace(mVcdFile, tmp_171_reg_717, "tmp_171_reg_717");
    sc_trace(mVcdFile, exitcond_fu_532_p2, "exitcond_fu_532_p2");
    sc_trace(mVcdFile, exitcond_reg_722, "exitcond_reg_722");
    sc_trace(mVcdFile, ci_2_fu_538_p2, "ci_2_fu_538_p2");
    sc_trace(mVcdFile, ci_2_reg_726, "ci_2_reg_726");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, j_13_fu_596_p2, "j_13_fu_596_p2");
    sc_trace(mVcdFile, conv3_w_load_reg_746, "conv3_w_load_reg_746");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, p2_o_2_load_reg_751, "p2_o_2_load_reg_751");
    sc_trace(mVcdFile, grp_fu_241_p2, "grp_fu_241_p2");
    sc_trace(mVcdFile, tmp_22_reg_756, "tmp_22_reg_756");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_fu_235_p2, "grp_fu_235_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, conv3_b_load_reg_766, "conv3_b_load_reg_766");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, tmp_20_reg_771, "tmp_20_reg_771");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, co_reg_112, "co_reg_112");
    sc_trace(mVcdFile, i_reg_123, "i_reg_123");
    sc_trace(mVcdFile, j_reg_134, "j_reg_134");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, i17_reg_145, "i17_reg_145");
    sc_trace(mVcdFile, m_reg_155, "m_reg_155");
    sc_trace(mVcdFile, sum_reg_167, "sum_reg_167");
    sc_trace(mVcdFile, j12_reg_179, "j12_reg_179");
    sc_trace(mVcdFile, tmp_19_fu_403_p2, "tmp_19_fu_403_p2");
    sc_trace(mVcdFile, n_reg_189, "n_reg_189");
    sc_trace(mVcdFile, sum_1_reg_200, "sum_1_reg_200");
    sc_trace(mVcdFile, ci_reg_212, "ci_reg_212");
    sc_trace(mVcdFile, sum_2_reg_223, "sum_2_reg_223");
    sc_trace(mVcdFile, co_cast4_fu_245_p1, "co_cast4_fu_245_p1");
    sc_trace(mVcdFile, tmp_174_cast_fu_376_p1, "tmp_174_cast_fu_376_p1");
    sc_trace(mVcdFile, tmp_181_cast_fu_561_p1, "tmp_181_cast_fu_561_p1");
    sc_trace(mVcdFile, tmp_189_cast_fu_591_p1, "tmp_189_cast_fu_591_p1");
    sc_trace(mVcdFile, grp_fu_235_p0, "grp_fu_235_p0");
    sc_trace(mVcdFile, grp_fu_235_p1, "grp_fu_235_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_155_fu_250_p3, "tmp_155_fu_250_p3");
    sc_trace(mVcdFile, tmp_156_fu_262_p3, "tmp_156_fu_262_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_258_p1, "p_shl2_cast_fu_258_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_270_p1, "p_shl3_cast_fu_270_p1");
    sc_trace(mVcdFile, tmp_157_fu_274_p2, "tmp_157_fu_274_p2");
    sc_trace(mVcdFile, i_cast3_cast_fu_306_p1, "i_cast3_cast_fu_306_p1");
    sc_trace(mVcdFile, tmp_159_fu_310_p2, "tmp_159_fu_310_p2");
    sc_trace(mVcdFile, tmp_148_fu_323_p3, "tmp_148_fu_323_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_315_p3, "p_shl4_cast_fu_315_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_331_p1, "p_shl5_cast_fu_331_p1");
    sc_trace(mVcdFile, tmp_fu_353_p2, "tmp_fu_353_p2");
    sc_trace(mVcdFile, j_cast2_cast_fu_367_p1, "j_cast2_cast_fu_367_p1");
    sc_trace(mVcdFile, tmp_161_fu_371_p2, "tmp_161_fu_371_p2");
    sc_trace(mVcdFile, tmp_s_fu_393_p2, "tmp_s_fu_393_p2");
    sc_trace(mVcdFile, ci_cast1_cast_fu_439_p1, "ci_cast1_cast_fu_439_p1");
    sc_trace(mVcdFile, tmp_162_fu_443_p2, "tmp_162_fu_443_p2");
    sc_trace(mVcdFile, tmp_151_fu_452_p3, "tmp_151_fu_452_p3");
    sc_trace(mVcdFile, p_shl_fu_460_p1, "p_shl_fu_460_p1");
    sc_trace(mVcdFile, tmp_175_cast_fu_448_p1, "tmp_175_cast_fu_448_p1");
    sc_trace(mVcdFile, tmp_163_fu_464_p2, "tmp_163_fu_464_p2");
    sc_trace(mVcdFile, tmp_164_fu_470_p2, "tmp_164_fu_470_p2");
    sc_trace(mVcdFile, tmp_167_fu_484_p3, "tmp_167_fu_484_p3");
    sc_trace(mVcdFile, tmp_168_fu_496_p3, "tmp_168_fu_496_p3");
    sc_trace(mVcdFile, p_shl8_cast_fu_492_p1, "p_shl8_cast_fu_492_p1");
    sc_trace(mVcdFile, p_shl9_cast_fu_504_p1, "p_shl9_cast_fu_504_p1");
    sc_trace(mVcdFile, tmp_169_fu_508_p2, "tmp_169_fu_508_p2");
    sc_trace(mVcdFile, tmp_184_cast_fu_514_p1, "tmp_184_cast_fu_514_p1");
    sc_trace(mVcdFile, tmp_170_fu_518_p2, "tmp_170_fu_518_p2");
    sc_trace(mVcdFile, p_shl10_cast_fu_544_p3, "p_shl10_cast_fu_544_p3");
    sc_trace(mVcdFile, tmp_165_fu_551_p2, "tmp_165_fu_551_p2");
    sc_trace(mVcdFile, tmp_166_fu_556_p2, "tmp_166_fu_556_p2");
    sc_trace(mVcdFile, p_shl6_cast_fu_566_p3, "p_shl6_cast_fu_566_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_573_p3, "p_shl7_cast_fu_573_p3");
    sc_trace(mVcdFile, tmp_172_fu_580_p2, "tmp_172_fu_580_p2");
    sc_trace(mVcdFile, tmp_173_fu_586_p2, "tmp_173_fu_586_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

convolution3::~convolution3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete lenet_wrapper_fadbkb_x_U30;
    delete lenet_wrapper_fmucud_x_U31;
}

void convolution3::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void convolution3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(tmp_21_fu_422_p2.read(), ap_const_lv1_1))) {
        ci_reg_212 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        ci_reg_212 = ci_2_reg_726.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_341_p2.read(), ap_const_lv1_1))) {
        co_reg_112 = co_2_reg_615.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        co_reg_112 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_381_p2.read()))) {
        i17_reg_145 = i_cast3_reg_625.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_fu_422_p2.read()))) {
        i17_reg_145 = i_18_fu_433_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_381_p2.read(), ap_const_lv1_1))) {
        i_reg_123 = h_reg_638.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond3_fu_290_p2.read(), ap_const_lv1_0))) {
        i_reg_123 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_fu_403_p2.read()))) {
        j12_reg_179 = j_cast2_reg_648.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(exitcond_reg_722.read(), ap_const_lv1_1))) {
        j12_reg_179 = j_13_fu_596_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_341_p2.read()))) {
        j_reg_134 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        j_reg_134 = w_reg_661.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_381_p2.read()))) {
        m_reg_155 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_fu_422_p2.read()))) {
        m_reg_155 = m_1_reg_674.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_fu_403_p2.read()))) {
        n_reg_189 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(exitcond_reg_722.read(), ap_const_lv1_1))) {
        n_reg_189 = n_1_reg_692.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_fu_403_p2.read()))) {
        sum_1_reg_200 = sum_reg_167.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(exitcond_reg_722.read(), ap_const_lv1_1))) {
        sum_1_reg_200 = sum_2_reg_223.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(tmp_21_fu_422_p2.read(), ap_const_lv1_1))) {
        sum_2_reg_223 = sum_1_reg_200.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        sum_2_reg_223 = grp_fu_235_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_381_p2.read()))) {
        sum_reg_167 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_fu_422_p2.read()))) {
        sum_reg_167 = sum_1_reg_200.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ci_2_reg_726 = ci_2_fu_538_p2.read();
        exitcond_reg_722 = exitcond_fu_532_p2.read();
        tmp_152_reg_702 = tmp_152_fu_476_p1.read();
        tmp_153_reg_707 = tmp_153_fu_480_p1.read();
        tmp_154_reg_712 = tmp_154_fu_524_p1.read();
        tmp_171_reg_717 = tmp_171_fu_528_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        co_2_reg_615 = co_2_fu_296_p2.read();
        tmp_158_reg_607 = tmp_158_fu_284_p2.read();
        tmp_166_cast_reg_602 = tmp_166_cast_fu_280_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond3_fu_290_p2.read(), ap_const_lv1_0))) {
        conv3_b_addr_reg_620 =  (sc_lv<4>) (co_cast4_fu_245_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        conv3_b_load_reg_766 = conv3_b_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        conv3_w_load_reg_746 = conv3_w_q0.read();
        p2_o_2_load_reg_751 = p2_o_2_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        h_reg_638 = h_fu_347_p2.read();
        i_cast3_reg_625 = i_cast3_fu_302_p1.read();
        tmp_160_reg_630 = tmp_160_fu_335_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_cast2_reg_648 = j_cast2_fu_363_p1.read();
        output_addr_reg_653 =  (sc_lv<11>) (tmp_174_cast_fu_376_p1.read());
        w_reg_661 = w_fu_387_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        m_1_reg_674 = m_1_fu_408_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        n_1_reg_692 = n_1_fu_427_p2.read();
        tmp_149_reg_679 = tmp_149_fu_414_p1.read();
        tmp_150_reg_684 = tmp_150_fu_418_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        tmp_20_reg_771 = grp_fu_235_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmp_22_reg_756 = grp_fu_241_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_381_p2.read()))) {
        tmp_cast_81_reg_666 = tmp_cast_81_fu_399_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_341_p2.read()))) {
        tmp_cast_reg_643 = tmp_cast_fu_359_p1.read();
    }
}

void convolution3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void convolution3::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void convolution3::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void convolution3::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void convolution3::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void convolution3::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void convolution3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void convolution3::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void convolution3::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void convolution3::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void convolution3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void convolution3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void convolution3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void convolution3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void convolution3::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void convolution3::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void convolution3::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void convolution3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond3_fu_290_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void convolution3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void convolution3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_290_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void convolution3::thread_ci_2_fu_538_p2() {
    ci_2_fu_538_p2 = (!ap_const_lv3_1.is_01() || !ci_reg_212.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(ci_reg_212.read()));
}

void convolution3::thread_ci_cast1_cast_fu_439_p1() {
    ci_cast1_cast_fu_439_p1 = esl_zext<10,3>(ci_reg_212.read());
}

void convolution3::thread_co_2_fu_296_p2() {
    co_2_fu_296_p2 = (!co_reg_112.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(co_reg_112.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void convolution3::thread_co_cast4_fu_245_p1() {
    co_cast4_fu_245_p1 = esl_zext<32,5>(co_reg_112.read());
}

void convolution3::thread_conv3_b_address0() {
    conv3_b_address0 = conv3_b_addr_reg_620.read();
}

void convolution3::thread_conv3_b_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        conv3_b_ce0 = ap_const_logic_1;
    } else {
        conv3_b_ce0 = ap_const_logic_0;
    }
}

void convolution3::thread_conv3_w_address0() {
    conv3_w_address0 =  (sc_lv<12>) (tmp_181_cast_fu_561_p1.read());
}

void convolution3::thread_conv3_w_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        conv3_w_ce0 = ap_const_logic_1;
    } else {
        conv3_w_ce0 = ap_const_logic_0;
    }
}

void convolution3::thread_exitcond1_fu_381_p2() {
    exitcond1_fu_381_p2 = (!j_reg_134.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_134.read() == ap_const_lv4_A);
}

void convolution3::thread_exitcond2_fu_341_p2() {
    exitcond2_fu_341_p2 = (!i_reg_123.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_123.read() == ap_const_lv4_A);
}

void convolution3::thread_exitcond3_fu_290_p2() {
    exitcond3_fu_290_p2 = (!co_reg_112.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(co_reg_112.read() == ap_const_lv5_10);
}

void convolution3::thread_exitcond_fu_532_p2() {
    exitcond_fu_532_p2 = (!ci_reg_212.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(ci_reg_212.read() == ap_const_lv3_6);
}

void convolution3::thread_grp_fu_235_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_235_p0 = sum_reg_167.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_235_p0 = sum_2_reg_223.read();
    } else {
        grp_fu_235_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void convolution3::thread_grp_fu_235_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_235_p1 = conv3_b_load_reg_766.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_235_p1 = tmp_22_reg_756.read();
    } else {
        grp_fu_235_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void convolution3::thread_h_fu_347_p2() {
    h_fu_347_p2 = (!i_reg_123.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_123.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void convolution3::thread_i_18_fu_433_p2() {
    i_18_fu_433_p2 = (!i17_reg_145.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i17_reg_145.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void convolution3::thread_i_cast3_cast_fu_306_p1() {
    i_cast3_cast_fu_306_p1 = esl_zext<9,4>(i_reg_123.read());
}

void convolution3::thread_i_cast3_fu_302_p1() {
    i_cast3_fu_302_p1 = esl_zext<32,4>(i_reg_123.read());
}

void convolution3::thread_j_13_fu_596_p2() {
    j_13_fu_596_p2 = (!j12_reg_179.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(j12_reg_179.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void convolution3::thread_j_cast2_cast_fu_367_p1() {
    j_cast2_cast_fu_367_p1 = esl_zext<12,4>(j_reg_134.read());
}

void convolution3::thread_j_cast2_fu_363_p1() {
    j_cast2_fu_363_p1 = esl_zext<32,4>(j_reg_134.read());
}

void convolution3::thread_m_1_fu_408_p2() {
    m_1_fu_408_p2 = (!m_reg_155.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(m_reg_155.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void convolution3::thread_n_1_fu_427_p2() {
    n_1_fu_427_p2 = (!ap_const_lv32_1.is_01() || !n_reg_189.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(n_reg_189.read()));
}

void convolution3::thread_output_r_address0() {
    output_r_address0 = output_addr_reg_653.read();
}

void convolution3::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void convolution3::thread_output_r_d0() {
    output_r_d0 = tmp_20_reg_771.read();
}

void convolution3::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void convolution3::thread_p2_o_2_address0() {
    p2_o_2_address0 =  (sc_lv<11>) (tmp_189_cast_fu_591_p1.read());
}

void convolution3::thread_p2_o_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p2_o_2_ce0 = ap_const_logic_1;
    } else {
        p2_o_2_ce0 = ap_const_logic_0;
    }
}

void convolution3::thread_p_shl10_cast_fu_544_p3() {
    p_shl10_cast_fu_544_p3 = esl_concat<11,2>(tmp_153_reg_707.read(), ap_const_lv2_0);
}

void convolution3::thread_p_shl2_cast_fu_258_p1() {
    p_shl2_cast_fu_258_p1 = esl_zext<9,8>(tmp_155_fu_250_p3.read());
}

void convolution3::thread_p_shl3_cast_fu_270_p1() {
    p_shl3_cast_fu_270_p1 = esl_zext<9,6>(tmp_156_fu_262_p3.read());
}

void convolution3::thread_p_shl4_cast_fu_315_p3() {
    p_shl4_cast_fu_315_p3 = esl_concat<9,3>(tmp_159_fu_310_p2.read(), ap_const_lv3_0);
}

void convolution3::thread_p_shl5_cast_fu_331_p1() {
    p_shl5_cast_fu_331_p1 = esl_zext<12,10>(tmp_148_fu_323_p3.read());
}

void convolution3::thread_p_shl6_cast_fu_566_p3() {
    p_shl6_cast_fu_566_p3 = esl_concat<8,4>(tmp_154_reg_712.read(), ap_const_lv4_0);
}

void convolution3::thread_p_shl7_cast_fu_573_p3() {
    p_shl7_cast_fu_573_p3 = esl_concat<11,1>(tmp_171_reg_717.read(), ap_const_lv1_0);
}

void convolution3::thread_p_shl8_cast_fu_492_p1() {
    p_shl8_cast_fu_492_p1 = esl_zext<8,7>(tmp_167_fu_484_p3.read());
}

void convolution3::thread_p_shl9_cast_fu_504_p1() {
    p_shl9_cast_fu_504_p1 = esl_zext<8,4>(tmp_168_fu_496_p3.read());
}

void convolution3::thread_p_shl_fu_460_p1() {
    p_shl_fu_460_p1 = esl_sext<32,12>(tmp_151_fu_452_p3.read());
}

void convolution3::thread_tmp_148_fu_323_p3() {
    tmp_148_fu_323_p3 = esl_concat<9,1>(tmp_159_fu_310_p2.read(), ap_const_lv1_0);
}

void convolution3::thread_tmp_149_fu_414_p1() {
    tmp_149_fu_414_p1 = j12_reg_179.read().range(12-1, 0);
}

void convolution3::thread_tmp_150_fu_418_p1() {
    tmp_150_fu_418_p1 = n_reg_189.read().range(13-1, 0);
}

void convolution3::thread_tmp_151_fu_452_p3() {
    tmp_151_fu_452_p3 = esl_concat<10,2>(tmp_162_fu_443_p2.read(), ap_const_lv2_0);
}

void convolution3::thread_tmp_152_fu_476_p1() {
    tmp_152_fu_476_p1 = tmp_164_fu_470_p2.read().range(13-1, 0);
}

void convolution3::thread_tmp_153_fu_480_p1() {
    tmp_153_fu_480_p1 = tmp_164_fu_470_p2.read().range(11-1, 0);
}

void convolution3::thread_tmp_154_fu_524_p1() {
    tmp_154_fu_524_p1 = tmp_170_fu_518_p2.read().range(8-1, 0);
}

void convolution3::thread_tmp_155_fu_250_p3() {
    tmp_155_fu_250_p3 = esl_concat<5,3>(co_reg_112.read(), ap_const_lv3_0);
}

void convolution3::thread_tmp_156_fu_262_p3() {
    tmp_156_fu_262_p3 = esl_concat<5,1>(co_reg_112.read(), ap_const_lv1_0);
}

void convolution3::thread_tmp_157_fu_274_p2() {
    tmp_157_fu_274_p2 = (!p_shl2_cast_fu_258_p1.read().is_01() || !p_shl3_cast_fu_270_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl2_cast_fu_258_p1.read()) - sc_biguint<9>(p_shl3_cast_fu_270_p1.read()));
}

void convolution3::thread_tmp_158_fu_284_p2() {
    tmp_158_fu_284_p2 = (!p_shl3_cast_fu_270_p1.read().is_01() || !p_shl2_cast_fu_258_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl3_cast_fu_270_p1.read()) + sc_biguint<9>(p_shl2_cast_fu_258_p1.read()));
}

void convolution3::thread_tmp_159_fu_310_p2() {
    tmp_159_fu_310_p2 = (!i_cast3_cast_fu_306_p1.read().is_01() || !tmp_158_reg_607.read().is_01())? sc_lv<9>(): (sc_biguint<9>(i_cast3_cast_fu_306_p1.read()) + sc_biguint<9>(tmp_158_reg_607.read()));
}

void convolution3::thread_tmp_160_fu_335_p2() {
    tmp_160_fu_335_p2 = (!p_shl4_cast_fu_315_p3.read().is_01() || !p_shl5_cast_fu_331_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl4_cast_fu_315_p3.read()) + sc_biguint<12>(p_shl5_cast_fu_331_p1.read()));
}

void convolution3::thread_tmp_161_fu_371_p2() {
    tmp_161_fu_371_p2 = (!tmp_160_reg_630.read().is_01() || !j_cast2_cast_fu_367_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_160_reg_630.read()) + sc_biguint<12>(j_cast2_cast_fu_367_p1.read()));
}

void convolution3::thread_tmp_162_fu_443_p2() {
    tmp_162_fu_443_p2 = (!ci_cast1_cast_fu_439_p1.read().is_01() || !tmp_166_cast_reg_602.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ci_cast1_cast_fu_439_p1.read()) + sc_bigint<10>(tmp_166_cast_reg_602.read()));
}

void convolution3::thread_tmp_163_fu_464_p2() {
    tmp_163_fu_464_p2 = (!p_shl_fu_460_p1.read().is_01() || !tmp_175_cast_fu_448_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_shl_fu_460_p1.read()) + sc_bigint<32>(tmp_175_cast_fu_448_p1.read()));
}

void convolution3::thread_tmp_164_fu_470_p2() {
    tmp_164_fu_470_p2 = (!m_reg_155.read().is_01() || !tmp_163_fu_464_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(m_reg_155.read()) + sc_biguint<32>(tmp_163_fu_464_p2.read()));
}

void convolution3::thread_tmp_165_fu_551_p2() {
    tmp_165_fu_551_p2 = (!p_shl10_cast_fu_544_p3.read().is_01() || !tmp_152_reg_702.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl10_cast_fu_544_p3.read()) + sc_biguint<13>(tmp_152_reg_702.read()));
}

void convolution3::thread_tmp_166_cast_fu_280_p1() {
    tmp_166_cast_fu_280_p1 = esl_sext<10,9>(tmp_157_fu_274_p2.read());
}

void convolution3::thread_tmp_166_fu_556_p2() {
    tmp_166_fu_556_p2 = (!tmp_150_reg_684.read().is_01() || !tmp_165_fu_551_p2.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_150_reg_684.read()) + sc_biguint<13>(tmp_165_fu_551_p2.read()));
}

void convolution3::thread_tmp_167_fu_484_p3() {
    tmp_167_fu_484_p3 = esl_concat<3,4>(ci_reg_212.read(), ap_const_lv4_0);
}

void convolution3::thread_tmp_168_fu_496_p3() {
    tmp_168_fu_496_p3 = esl_concat<3,1>(ci_reg_212.read(), ap_const_lv1_0);
}

void convolution3::thread_tmp_169_fu_508_p2() {
    tmp_169_fu_508_p2 = (!p_shl8_cast_fu_492_p1.read().is_01() || !p_shl9_cast_fu_504_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl8_cast_fu_492_p1.read()) - sc_biguint<8>(p_shl9_cast_fu_504_p1.read()));
}

void convolution3::thread_tmp_170_fu_518_p2() {
    tmp_170_fu_518_p2 = (!i17_reg_145.read().is_01() || !tmp_184_cast_fu_514_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(i17_reg_145.read()) + sc_bigint<32>(tmp_184_cast_fu_514_p1.read()));
}

void convolution3::thread_tmp_171_fu_528_p1() {
    tmp_171_fu_528_p1 = tmp_170_fu_518_p2.read().range(11-1, 0);
}

void convolution3::thread_tmp_172_fu_580_p2() {
    tmp_172_fu_580_p2 = (!p_shl6_cast_fu_566_p3.read().is_01() || !p_shl7_cast_fu_573_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl6_cast_fu_566_p3.read()) - sc_biguint<12>(p_shl7_cast_fu_573_p3.read()));
}

void convolution3::thread_tmp_173_fu_586_p2() {
    tmp_173_fu_586_p2 = (!tmp_149_reg_679.read().is_01() || !tmp_172_fu_580_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_149_reg_679.read()) + sc_biguint<12>(tmp_172_fu_580_p2.read()));
}

void convolution3::thread_tmp_174_cast_fu_376_p1() {
    tmp_174_cast_fu_376_p1 = esl_zext<32,12>(tmp_161_fu_371_p2.read());
}

void convolution3::thread_tmp_175_cast_fu_448_p1() {
    tmp_175_cast_fu_448_p1 = esl_sext<32,10>(tmp_162_fu_443_p2.read());
}

void convolution3::thread_tmp_181_cast_fu_561_p1() {
    tmp_181_cast_fu_561_p1 = esl_zext<32,13>(tmp_166_fu_556_p2.read());
}

void convolution3::thread_tmp_184_cast_fu_514_p1() {
    tmp_184_cast_fu_514_p1 = esl_sext<32,8>(tmp_169_fu_508_p2.read());
}

void convolution3::thread_tmp_189_cast_fu_591_p1() {
    tmp_189_cast_fu_591_p1 = esl_zext<32,12>(tmp_173_fu_586_p2.read());
}

void convolution3::thread_tmp_19_fu_403_p2() {
    tmp_19_fu_403_p2 = (!i17_reg_145.read().is_01() || !tmp_cast_reg_643.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i17_reg_145.read()) < sc_bigint<32>(tmp_cast_reg_643.read()));
}

void convolution3::thread_tmp_21_fu_422_p2() {
    tmp_21_fu_422_p2 = (!j12_reg_179.read().is_01() || !tmp_cast_81_reg_666.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j12_reg_179.read()) < sc_bigint<32>(tmp_cast_81_reg_666.read()));
}

void convolution3::thread_tmp_cast_81_fu_399_p1() {
    tmp_cast_81_fu_399_p1 = esl_zext<32,4>(tmp_s_fu_393_p2.read());
}

void convolution3::thread_tmp_cast_fu_359_p1() {
    tmp_cast_fu_359_p1 = esl_zext<32,4>(tmp_fu_353_p2.read());
}

void convolution3::thread_tmp_fu_353_p2() {
    tmp_fu_353_p2 = (!i_reg_123.read().is_01() || !ap_const_lv4_5.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_123.read()) + sc_biguint<4>(ap_const_lv4_5));
}

void convolution3::thread_tmp_s_fu_393_p2() {
    tmp_s_fu_393_p2 = (!j_reg_134.read().is_01() || !ap_const_lv4_5.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_134.read()) + sc_biguint<4>(ap_const_lv4_5));
}

void convolution3::thread_w_fu_387_p2() {
    w_fu_387_p2 = (!j_reg_134.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_134.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void convolution3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond3_fu_290_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond2_fu_341_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond1_fu_381_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_fu_403_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_fu_422_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(exitcond_reg_722.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<25>) ("XXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

