# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/thomas/ece527/mp2/PmodOLED_Source/mp2_partA.srcs/sources_1/ip/charLib/charLib.xci
# IP: The module: 'charLib' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/thomas/ece527/mp2/PmodOLED_Source/mp2_partA.srcs/sources_1/ip/charLib/charLib_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'charLib'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/thomas/ece527/mp2/PmodOLED_Source/mp2_partA.srcs/sources_1/ip/charLib/charLib.xci
# IP: The module: 'charLib' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/thomas/ece527/mp2/PmodOLED_Source/mp2_partA.srcs/sources_1/ip/charLib/charLib_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'charLib'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
