# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_xbar_0/mp1a_hardware_xbar_0.xci
# IP: The module: 'mp1a_hardware_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_xbar_0/mp1a_hardware_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp1a_hardware_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_xbar_0/mp1a_hardware_xbar_0.xci
# IP: The module: 'mp1a_hardware_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/ece527/mp2/mp2a.srcs/sources_1/bd/mp1a_hardware/ip/mp1a_hardware_xbar_0/mp1a_hardware_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp1a_hardware_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
