// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XFC6_H
#define XFC6_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xfc6_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XFc6_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XFc6;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XFc6_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XFc6_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XFc6_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XFc6_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XFc6_Initialize(XFc6 *InstancePtr, u16 DeviceId);
XFc6_Config* XFc6_LookupConfig(u16 DeviceId);
int XFc6_CfgInitialize(XFc6 *InstancePtr, XFc6_Config *ConfigPtr);
#else
int XFc6_Initialize(XFc6 *InstancePtr, const char* InstanceName);
int XFc6_Release(XFc6 *InstancePtr);
#endif

void XFc6_Start(XFc6 *InstancePtr);
u32 XFc6_IsDone(XFc6 *InstancePtr);
u32 XFc6_IsIdle(XFc6 *InstancePtr);
u32 XFc6_IsReady(XFc6 *InstancePtr);
void XFc6_EnableAutoRestart(XFc6 *InstancePtr);
void XFc6_DisableAutoRestart(XFc6 *InstancePtr);
u32 XFc6_Get_return(XFc6 *InstancePtr);

void XFc6_Set_input_r(XFc6 *InstancePtr, u32 Data);
u32 XFc6_Get_input_r(XFc6 *InstancePtr);
void XFc6_Set_weights(XFc6 *InstancePtr, u32 Data);
u32 XFc6_Get_weights(XFc6 *InstancePtr);
void XFc6_Set_bias(XFc6 *InstancePtr, u32 Data);
u32 XFc6_Get_bias(XFc6 *InstancePtr);
void XFc6_Set_output_r(XFc6 *InstancePtr, u32 Data);
u32 XFc6_Get_output_r(XFc6 *InstancePtr);

void XFc6_InterruptGlobalEnable(XFc6 *InstancePtr);
void XFc6_InterruptGlobalDisable(XFc6 *InstancePtr);
void XFc6_InterruptEnable(XFc6 *InstancePtr, u32 Mask);
void XFc6_InterruptDisable(XFc6 *InstancePtr, u32 Mask);
void XFc6_InterruptClear(XFc6 *InstancePtr, u32 Mask);
u32 XFc6_InterruptGetEnabled(XFc6 *InstancePtr);
u32 XFc6_InterruptGetStatus(XFc6 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
